import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Export a timetable DOM element to a PDF file.
 * @param {string} elementId - ID of the DOM element to capture
 * @param {object} opts - { fileName, institutionName, title, academicYear, semester }
 */
export async function exportToPDF(elementId, opts = {}) {
  const {
    fileName = 'timetable.pdf',
    institutionName = 'Institution',
    title = 'Timetable',
    academicYear = '',
    semester = '',
  } = opts;

  const element = document.getElementById(elementId);
  if (!element) throw new Error(`Element #${elementId} not found`);

  // Temporarily make element fully visible for capture
  const originalStyle = element.getAttribute('style') || '';
  element.style.background = '#ffffff';

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: '#ffffff',
    logging: false,
    scrollX: 0,
    scrollY: 0,
  });

  element.setAttribute('style', originalStyle);

  const imgData = canvas.toDataURL('image/png');
  const imgW = canvas.width;
  const imgH = canvas.height;

  // A4 landscape if wide, else portrait
  const isLandscape = imgW > imgH;
  const pdf = new jsPDF({
    orientation: isLandscape ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 12;

  // ── Header ──
  pdf.setFillColor(79, 70, 229); // indigo
  pdf.rect(0, 0, pageW, 22, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(13);
  pdf.setFont('helvetica', 'bold');
  pdf.text(institutionName, margin, 10);

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  const subLine = [title, academicYear, semester].filter(Boolean).join('  |  ');
  pdf.text(subLine, margin, 17);

  // Generated date (right-aligned)
  const dateStr = `Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`;
  const dateW = pdf.getTextWidth(dateStr);
  pdf.text(dateStr, pageW - margin - dateW, 17);

  // ── Image ──
  const contentY = 26;
  const availW = pageW - margin * 2;
  const scale = availW / (imgW / (96 / 25.4)); // px to mm at 96 DPI
  const scaledH = (imgH / (96 / 25.4)) * scale / (imgW / (96 / 25.4));

  // Scale to fit page
  const maxH = pageH - contentY - margin;
  const finalScale = Math.min(availW / (imgW / 3.7795), maxH / (imgH / 3.7795));
  const finalW = (imgW / 3.7795) * finalScale;
  const finalH = (imgH / 3.7795) * finalScale;

  pdf.addImage(imgData, 'PNG', margin, contentY, finalW, finalH);

  // ── Footer ──
  pdf.setTextColor(150, 150, 150);
  pdf.setFontSize(7.5);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Generated by EduSchedule — Professional Timetable Management System', margin, pageH - 5);

  pdf.save(fileName);
}

/**
 * Export ALL class timetables as a multi-page PDF.
 */
export async function exportAllTimetablesPDF(classIds, getElementId, opts = {}) {
  const { institutionName = 'Institution', academicYear = '', semester = '' } = opts;

  const isLandscape = true;
  const pdf = new jsPDF({
    orientation: isLandscape ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 12;

  for (let i = 0; i < classIds.length; i++) {
    const { classId, className } = classIds[i];
    const elementId = getElementId(classId);
    const element = document.getElementById(elementId);
    if (!element) continue;

    if (i > 0) pdf.addPage();

    // Header
    pdf.setFillColor(79, 70, 229);
    pdf.rect(0, 0, pageW, 22, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(13);
    pdf.setFont('helvetica', 'bold');
    pdf.text(institutionName, margin, 10);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const subLine = [`Class ${className} Timetable`, academicYear, semester].filter(Boolean).join('  |  ');
    pdf.text(subLine, margin, 17);

    const dateStr = `Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`;
    const dateW = pdf.getTextWidth(dateStr);
    pdf.text(dateStr, pageW - margin - dateW, 17);

    const originalBg = element.style.background;
    element.style.background = '#ffffff';
    const canvas = await html2canvas(element, {
      scale: 2, useCORS: true, backgroundColor: '#ffffff', logging: false,
    });
    element.style.background = originalBg;

    const imgData = canvas.toDataURL('image/png');
    const contentY = 26;
    const availW = pageW - margin * 2;
    const maxH = pageH - contentY - margin - 8;
    const finalScale = Math.min(availW / (canvas.width / 3.7795), maxH / (canvas.height / 3.7795));
    const finalW = (canvas.width / 3.7795) * finalScale;
    const finalH = (canvas.height / 3.7795) * finalScale;
    pdf.addImage(imgData, 'PNG', margin, contentY, finalW, finalH);

    pdf.setTextColor(150, 150, 150);
    pdf.setFontSize(7.5);
    pdf.text(`Page ${i + 1} of ${classIds.length}  |  EduSchedule`, margin, pageH - 5);
  }

  pdf.save(`${institutionName.replace(/\s+/g, '_')}_Timetables.pdf`);
}
